//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerDetail
    {
        public int ID { get; set; }
        public int ManagerID { get; set; }
        public decimal AnnualSalary { get; set; }
        public decimal MaxExpenseAccount { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
